config/routes.rb
Rails.application.routes.draw do
  root to: "pages#welcome"
  get "/association", to: "pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaVeloterie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="full_logo">
  <%= image_tag "logo_sans_outils.PNG", :class => "background" %>
  <%= image_tag ("Tool1"), :class => "tool" %>
  <%= image_tag ("Tool2"), :class => "tool" %>
  <%= image_tag ("Tool3"), :class => "tool" %>
  <%= image_tag ("Tool4"), :class => "tool" %>
  <%= image_tag ("Tool5"), :class => "tool" %>
  <%= image_tag ("Tool6"), :class => "tool" %>
  <%= image_tag ("Tool7"), :class => "tool" %>
  <%= image_tag ("Tool8"), :class => "tool" %>
</div>

app/views/pages/welcome.html.erb
<div class="welcome" data-controller="hello">
  <%= link_to association_path do %>
    <%= image_tag("logo_couleur", class: "logo") %>
  <% end %>
</div>


<script>

</script>